# Generated by Django 4.0.3 on 2023-12-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_slidermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtolyeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='img/%y')),
                ('date_ato', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date_ato',),
            },
        ),
    ]
